version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      maven: 3.8
    commands:
      - echo Using pre-installed Maven and Java
  build:
    commands:
      - echo Building the project...
      - mvn clean install
artifacts:
  files:
    - target/basic-demo-pipeline.jar