version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - apt-get update
      - apt-get install -y maven
  build:
    commands:
      - echo Building the project...
      - mvn clean install
artifacts:
  files:
    - target/basic-demo-pipeline.jar
